class PreLimit:
    modelnumbers = [
        "Canon New FD 50mm f/1.4",
        "Canon Autoboy D5",
        "Canon 220EX",
        "Canon New FD 35mm F/2.8",
        "Contax TLA-140",
        "CONTAX Soft Lens Case MCL-6",
        "Fidelity Elite 4x5 Film Holder",
        "Fujifilm PA-45",
        "Mamiya RZ67 Polaroid Film Holder",
        "Mamiya RZ67 120 Film Back",
        "Mamiya RZ67 645 Film Back",
        "Mamiya RZ67 RB67ベローズフード",
        "Mamiya RZ67 WINDER",
        "Mamiya RB / RZ Dual Shutter release cable",
        "Mamiya RZ67 Polaroid Film Back Holder",
        "Mamiya 645 Film Back 120 Insert for 645 Pro TL Super",
        "Mamiya RB67 Pro S 120 Film Back",
        "Mamiya 50mm Universal Press finder",
        "Mamiya 645 RB67 77mm Round Rubber Lens Hood",
        "Mamiya Left Hand Grip L rb67",
        "Minolta Flash Meter III",
        "Minolta 50 F1.7",
        "MInolta AF 70-210mm F4",
        "Minolta PROGRAM 5400 HS",
        "Minolta Auto Meter III",
        "Minolta 300-S MD 2x Tele Converter",
        "Nikon AF NIKKOR 70-210mm F4-5.6 D",
        "Nikon Teleconverter TC-201 2X",
        "Nikon AF NIKKOR 28-85mm F3.5-4.5",
        "Nikon Nikkor AI 80-200mm F4.5",
        "Nikon Teleconverter TC-200 2X",
        "Nikon Waist-Level Finder DW-3",
        "Nikon Nikkor Auto S 50mm f1.4",
        "Nikon Nikkor AI 50mm f1.8",
        "Nikon NIKKOR-S Auto 5cm F2",
        "Nikon New Nikkor 200mm f4",
        "Nikon New Nikkor 135mm F2.8",
        "Nikon New Nikkor 135mm F3.5",
        "Nikon New Nikkor 28mm F3.5",
        "Nikon Ai Nikkor 28mm F3.5",
        "Nikon Ai-s Zoom Nikkor 28-85mm F3.5-4.5",
        "Nikon Nikkor-H・C Auto 50mm F2",
        "Nikon F5 Strap",
        "nikon SB-24",
        "nikon DE-3(F3HP)",
        "nikon SB-27",
        "Nikkor-S.C 50mm F/1.4",
        "Nikon Ai-s 100-300mm F/5.6",
        "Nikon AF 70-210mm F/4-5.6 D",
        "Nikon DW-3",
        "Nikon SB-23",
        "Olympus 50mm 1.8",
        "Olympus Pen EE3",
        "Olympus Trip 35",
        "Olympus XA",
        "Olympus OM System G.Zuiko Auto-W 35mm F/2.8",
        "Pentax 645 120 Film Back",
        "Asahi Pentax 6x7 Prism Eyelevel Viewfinder",
        "Pentax 50mm F 1.8",
        "Pentax SMC 50mm F 1.4",
        "Pentax 55mm F1.8",
        "Pentax 35mm F 2.8",
        "Pentax 35mm F 3.5",
        "Pentax 28mm F 2.8",
        "Pentax 28mm F3.5",
        "Pentax 645, 67 Strap",
        "Pentax 645 finder Flip-Up Magnifier",
        "Pentax Eyepiece Magnifier Viewfinder for 6x7 67 67II",
        "Pentax SMC Takumar 6x7 75mm F/4.5 Lens",
        "Pentax 645 120 filmback",
        "Pentax Super Takumar 55mm F/1.8",
        "Pentax SMC Pentax-M 50mm F/1.4",
        "Sekonic Studio Deluxe L-398"
    ]

