class Sekonic:
    modelnumbers = [
        "Sekonic P-I",
        "Sekonic P-II",
        "Sekonic CB-I and B-I Baby",
        "Sekonic B-II",
        "Sekonic LC-I",
        "Sekonic LC-II",
        "Sekonic L-I",
        "Sekonic L-II",
        "Sekonic L-III",
        "Sekonic L-IIIB",
        "Sekonic L-IV",
        "Sekonic L-V",
        "Sekonic L-VI",
        "Sekonic L-7",
        "Sekonic L-7B",
        "Sekonic L-8B",
        "Sekonic L-20B",
        "Sekonic L-28A",
        "Sekonic L-28A2",
        "Sekonic L-28C",
        "Sekonic L-28C2",
        "Sekonic L-36",
        "Sekonic L-38",
        "Sekonic L-54",
        "Sekonic L-58",
        "Sekonic L-78",
        "Sekonic L-86",
        "Sekonic L-86B",
        "Sekonic L-88",
        "Sekonic L-96",
        "Sekonic L-98",
        "Sekonic L-99",
        "Sekonic L-208",
        "Sekonic L-104S",
        "Sekonic L-136",
        "Sekonic L-138",
        "Sekonic L-158",
        "Sekonic L-164",
        "Sekonic L-164B",
        "Sekonic L-164C",
        "Sekonic L-188",
        "Sekonic L-206",
        "Sekonic L-208",
        "Sekonic L-216",
        "Sekonic L-216B",
        "Sekonic L-218",
        "Sekonic L-228",
        "Sekonic L-248",
        "Sekonic L-256",
        "Sekonic L-256D",
        "Sekonic L-258",
        "Sekonic L-308",
        "Sekonic L-308B",
        "Sekonic L-308BII",
        "Sekonic L-308S",
        "Sekonic L-318",
        "Sekonic L-318B",
        "Sekonic L-328",
        "Sekonic L-358",
        "Sekonic L-398",
        "Sekonic L-398M",
        "Sekonic L-398A",
        "Sekonic L-408",
        "Sekonic L-418",
        "Sekonic L-428",
        "Sekonic L-438",
        "Sekonic L-508",
        "Sekonic L-448",
        "Sekonic L-458",
        "Sekonic L-478DR-U",
        "Sekonic L-488",
        "Sekonic L-508",
        "Sekonic L-508",
        "Sekonic L-518",
        "Sekonic L-558 and L-558R",
        "Sekonic L-558",
        "Sekonic L-608",
        "Sekonic L-718",
        "Sekonic L-758",
        "Sekonic L-758DR",
        "Sekonic L-778",
    ]

    _modelnumbers = [
        "Sekonic P-I Perfect",
        "Sekonic P-II Perfect",
        "Sekonic CB-I and B-I Baby",
        "Sekonic B-II Baby",
        "Sekonic LC-I Honest",
        "Sekonic LC-II Clip-On",
        "Sekonic L-I",
        "Sekonic L-II Universal",
        "Sekonic L-III Professional",
        "Sekonic L-IIIB Professional",
        "Sekonic L-IV",
        "Sekonic L-V New Professional",
        "Sekonic L-VI Leader",
        "Sekonic L-7 Baby",
        "Sekonic L-7B FR-Meter",
        "Sekonic L-8B Director",
        "Sekonic L-20B Table Light Checker",
        "Sekonic L-28A Studio S",
        "Sekonic L-28A2 Studio S2",
        "Sekonic L-28C Studio Deluxe",
        "Sekonic L-28C2 Studio Deluxe",
        "Sekonic L-36 Leader Deluxe II",
        "Sekonic L-38 Auto Leader",
        "Sekonic L-54 Pet Polaroid-Meter",
        "Sekonic L-54 Pet LV-Meter",
        "Sekonic L-54 Pet Snap-Meter",
        "Sekonic L-54 Movie Pet",
        "Sekonic L-58 Micro Mat",
        "Sekonic L-78 New Movie Meter",
        "Sekonic L-86 Autolumi",
        "Sekonic L-86B Autolumi",
        "Sekonic L-88 Micro Light Meter",
        "Sekonic L-96 Super Micro Light",
        "Sekonic L-98 Micro-Leader",
        "Sekonic L-99 Auto Leader II",
        "Sekonic L-208 Twinmate",
        "Sekonic L-104S Master IV",
        "Sekonic L-136 Microclip-on",
        "Sekonic L-138 Micro Junior",
        "Sekonic L-158 Auto Lumi",
        "Sekonic L-164 Marine",
        "Sekonic L-164B Marine Meter II",
        "Sekonic L-164C Marine Meter II",
        "Sekonic L-188 Auto-Leader",
        "Sekonic L-206 Viewmeter",
        "Sekonic L-208 Twinmate",
        "Sekonic L-216 Autorange",
        "Sekonic L-216B Autorange",
        "Sekonic L-218 Apex",
        "Sekonic L-228 Zoom-Meter",
        "Sekonic L-248 Multi-Lumi",
        "Sekonic L-256 Flashmeter",
        "Sekonic L-256D Flashmeter",
        "Sekonic L-258 Light Checker",
        "Sekonic L-308 Flashmate",
        "Sekonic L-308B Flashmate",
        "Sekonic L-308BII Flashmate",
        "Sekonic L-308S Flashmate",
        "Sekonic L-318 Digi-Light",
        "Sekonic L-318B Digi-Light",
        "Sekonic L-328 Digi-Light F",
        "Sekonic L-358 Flash Master",
        "Sekonic L-398 Studio Deluxe",
        "Sekonic L-398M Studio Deluxe II",
        "Sekonic L-398A Studio Deluxe III",
        "Sekonic L-408 Multimaster",
        "Sekonic L-418 Autometer",
        "Sekonic L-428 System-Meter",
        "Sekonic L-438 View-Spotmeter",
        "Sekonic L-508 Zoom-Master",
        "Sekonic L-448 Studio-Auto II",
        "Sekonic L-458 Digi-Flash",
        "Sekonic L-478DR-U",
        "Sekonic L-488 Digi-Spot",
        "Sekonic L-508 Zoom-Master",
        "Sekonic L-508 Cine Zoom-Master",
        "Sekonic L-518 Digipro X-1",
        "Sekonic L-558 and L-558R Dualmaster",
        "Sekonic L-558 Cine Dualmaster",
        "Sekonic L-608 Superzoom-Master",
        "Sekonic L-608 Cine Superzoom-Master",
        "Sekonic L-718 Digi-Master",
        "Sekonic L-758 Cine Digital Master",
        "Sekonic L-758DR Digital Master",
        "Sekonic L-778 Dual-Spot F",
    ]
